### PR TITLE
feat: Update YT Explode

### LINKED ISSUE #50: YT download failing
Attempt to download https://youtu.be/AU56pqcKYeY results in:
 [Unknown error](https://www.dropbox.com/s/10pkv6bzi2l16ed/screenshot_20210726-041144.png?dl=1)

### PR DESCRIPTION
**Pull request by ashwinkey04**
Fixes #50

### CODE REVIEW

**Comment by switchcomb** [comment]
Thanks for the quick turnaround. I just tried it now again with the same two URLs from issue 50 but still getting an error message:

Screenshot_20210908-082458

Tried it also with https://youtu.be/Te7wibdDeCw and goy a similar message:

Screenshot_20210908-082905

**Comment by ashwinkey04** [comment]
YouTube doesn't seem to allow us to download a few copyrighted videos. We seem to get an error popup showing "Bad state No element" in the new version. The screenshots you attached are showing the error message from previous version. Could you confirm if you have v1.0.6?

PS: I tried downloading https://youtu.be/AU56pqcKYeY and it worked. Wasn't able to download the video you mentioned in this PR though

**Comment by switchcomb** [comment]
Confirmed, the first YT link I was able to download via raag after installing version 1.0.6 from this Github; I had tried to do it earlier using v1.0.5 downloaded from F-Droid. Thanks again!

**Comment by ashwinkey04** [comment]
@switchcomb You're welcome :)

**Pull request merged**
